export const prestamos = [
  {
    id:                1,
    usuario_id:        3,
    tipo_credito:      "Vivienda",
    monto_solicitado:  9500000,
    monto_aprobado:    9500000,
    tasa_interes:      1.0,
    plazo_meses:       6,
    fecha_solicitud:   "2024-05-22",
    fecha_aprobacion:  "2024-05-29",
    estado:            "aprobado",
    cuotas_pendientes: 5
  },
  {
    id:                2,
    usuario_id:        1,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  2000000,
    monto_aprobado:    1600000,
    tasa_interes:      0.9,
    plazo_meses:       3,
    fecha_solicitud:   "2024-08-11",
    fecha_aprobacion:  "2024-08-14",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                3,
    usuario_id:        3,
    tipo_credito:      "Educativo",
    monto_solicitado:  7000000,
    monto_aprobado:    6700000,
    tasa_interes:      1.5,
    plazo_meses:       36,
    fecha_solicitud:   "2025-12-19",
    fecha_aprobacion:  "2025-12-25",
    estado:            "aprobado",
    cuotas_pendientes: 15
  },
  {
    id:                4,
    usuario_id:        2,
    tipo_credito:      "Emergencia",
    monto_solicitado:  1000000,
    monto_aprobado:    800000,
    tasa_interes:      1.5,
    plazo_meses:       6,
    fecha_solicitud:   "2025-03-08",
    fecha_aprobacion:  "2025-03-12",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                5,
    usuario_id:        1,
    tipo_credito:      "Libranza",
    monto_solicitado:  11500000,
    monto_aprobado:    11300000,
    tasa_interes:      0.9,
    plazo_meses:       3,
    fecha_solicitud:   "2025-01-24",
    fecha_aprobacion:  "2025-01-26",
    estado:            "aprobado",
    cuotas_pendientes: 2
  },
  {
    id:                6,
    usuario_id:        3,
    tipo_credito:      "Libranza",
    monto_solicitado:  2000000,
    monto_aprobado:    1700000,
    tasa_interes:      1.2,
    plazo_meses:       36,
    fecha_solicitud:   "2025-07-03",
    fecha_aprobacion:  "2025-07-05",
    estado:            "aprobado",
    cuotas_pendientes: 6
  },
  {
    id:                7,
    usuario_id:        3,
    tipo_credito:      "Convenio",
    monto_solicitado:  12500000,
    monto_aprobado:    12500000,
    tasa_interes:      1.0,
    plazo_meses:       24,
    fecha_solicitud:   "2025-12-22",
    fecha_aprobacion:  "2025-12-24",
    estado:            "aprobado",
    cuotas_pendientes: 22
  },
  {
    id:                8,
    usuario_id:        1,
    tipo_credito:      "Vacacional",
    monto_solicitado:  3500000,
    monto_aprobado:    null,
    tasa_interes:      1.8,
    plazo_meses:       6,
    fecha_solicitud:   "2024-04-13",
    fecha_aprobacion:  null,
    estado:            "pendiente",
    cuotas_pendientes: 0
  },
  {
    id:                9,
    usuario_id:        2,
    tipo_credito:      "Libranza",
    monto_solicitado:  12500000,
    monto_aprobado:    12000000,
    tasa_interes:      1.1,
    plazo_meses:       6,
    fecha_solicitud:   "2024-12-29",
    fecha_aprobacion:  "2025-01-01",
    estado:            "aprobado",
    cuotas_pendientes: 3
  },
  {
    id:                10,
    usuario_id:        3,
    tipo_credito:      "Vivienda",
    monto_solicitado:  3000000,
    monto_aprobado:    null,
    tasa_interes:      1.5,
    plazo_meses:       24,
    fecha_solicitud:   "2024-06-24",
    fecha_aprobacion:  null,
    estado:            "rechazado",
    cuotas_pendientes: 0
  },
  {
    id:                11,
    usuario_id:        3,
    tipo_credito:      "Vacacional",
    monto_solicitado:  6000000,
    monto_aprobado:    null,
    tasa_interes:      1.2,
    plazo_meses:       18,
    fecha_solicitud:   "2024-10-03",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                12,
    usuario_id:        3,
    tipo_credito:      "Libranza",
    monto_solicitado:  8000000,
    monto_aprobado:    null,
    tasa_interes:      1.1,
    plazo_meses:       36,
    fecha_solicitud:   "2024-02-27",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                13,
    usuario_id:        1,
    tipo_credito:      "Vacacional",
    monto_solicitado:  11000000,
    monto_aprobado:    null,
    tasa_interes:      1.1,
    plazo_meses:       18,
    fecha_solicitud:   "2024-03-08",
    fecha_aprobacion:  null,
    estado:            "pendiente",
    cuotas_pendientes: 0
  },
  {
    id:                14,
    usuario_id:        1,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  19000000,
    monto_aprobado:    null,
    tasa_interes:      1.1,
    plazo_meses:       36,
    fecha_solicitud:   "2024-08-05",
    fecha_aprobacion:  null,
    estado:            "rechazado",
    cuotas_pendientes: 0
  },
  {
    id:                15,
    usuario_id:        3,
    tipo_credito:      "Libranza",
    monto_solicitado:  15500000,
    monto_aprobado:    15000000,
    tasa_interes:      1.1,
    plazo_meses:       6,
    fecha_solicitud:   "2024-05-22",
    fecha_aprobacion:  "2024-05-25",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                16,
    usuario_id:        3,
    tipo_credito:      "Libranza",
    monto_solicitado:  19500000,
    monto_aprobado:    19400000,
    tasa_interes:      1.3,
    plazo_meses:       18,
    fecha_solicitud:   "2025-02-12",
    fecha_aprobacion:  "2025-02-16",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                17,
    usuario_id:        1,
    tipo_credito:      "Educativo",
    monto_solicitado:  3500000,
    monto_aprobado:    3000000,
    tasa_interes:      1.8,
    plazo_meses:       3,
    fecha_solicitud:   "2024-04-22",
    fecha_aprobacion:  "2024-04-25",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                18,
    usuario_id:        1,
    tipo_credito:      "Educativo",
    monto_solicitado:  14500000,
    monto_aprobado:    null,
    tasa_interes:      0.9,
    plazo_meses:       24,
    fecha_solicitud:   "2025-01-29",
    fecha_aprobacion:  null,
    estado:            "pendiente",
    cuotas_pendientes: 0
  },
  {
    id:                19,
    usuario_id:        2,
    tipo_credito:      "Libranza",
    monto_solicitado:  15500000,
    monto_aprobado:    15000000,
    tasa_interes:      1.1,
    plazo_meses:       24,
    fecha_solicitud:   "2025-07-20",
    fecha_aprobacion:  "2025-07-22",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                20,
    usuario_id:        3,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  18000000,
    monto_aprobado:    18000000,
    tasa_interes:      1.8,
    plazo_meses:       12,
    fecha_solicitud:   "2025-10-18",
    fecha_aprobacion:  "2025-10-22",
    estado:            "aprobado",
    cuotas_pendientes: 5
  },
  {
    id:                21,
    usuario_id:        2,
    tipo_credito:      "Libranza",
    monto_solicitado:  1000000,
    monto_aprobado:    900000,
    tasa_interes:      1.5,
    plazo_meses:       36,
    fecha_solicitud:   "2024-09-26",
    fecha_aprobacion:  "2024-10-02",
    estado:            "aprobado",
    cuotas_pendientes: 33
  },
  {
    id:                22,
    usuario_id:        1,
    tipo_credito:      "Vacacional",
    monto_solicitado:  10500000,
    monto_aprobado:    null,
    tasa_interes:      1.3,
    plazo_meses:       36,
    fecha_solicitud:   "2025-09-15",
    fecha_aprobacion:  null,
    estado:            "pendiente",
    cuotas_pendientes: 0
  },
  {
    id:                23,
    usuario_id:        1,
    tipo_credito:      "Educativo",
    monto_solicitado:  6000000,
    monto_aprobado:    5600000,
    tasa_interes:      1.8,
    plazo_meses:       24,
    fecha_solicitud:   "2025-06-27",
    fecha_aprobacion:  "2025-06-29",
    estado:            "aprobado",
    cuotas_pendientes: 11
  },
  {
    id:                24,
    usuario_id:        2,
    tipo_credito:      "Libranza",
    monto_solicitado:  12500000,
    monto_aprobado:    12100000,
    tasa_interes:      1.0,
    plazo_meses:       12,
    fecha_solicitud:   "2024-02-29",
    fecha_aprobacion:  "2024-03-03",
    estado:            "aprobado",
    cuotas_pendientes: 2
  },
  {
    id:                25,
    usuario_id:        1,
    tipo_credito:      "Convenio",
    monto_solicitado:  3000000,
    monto_aprobado:    null,
    tasa_interes:      1.8,
    plazo_meses:       24,
    fecha_solicitud:   "2024-05-08",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                26,
    usuario_id:        1,
    tipo_credito:      "Vacacional",
    monto_solicitado:  18500000,
    monto_aprobado:    null,
    tasa_interes:      1.1,
    plazo_meses:       6,
    fecha_solicitud:   "2025-06-24",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                27,
    usuario_id:        3,
    tipo_credito:      "Libranza",
    monto_solicitado:  7500000,
    monto_aprobado:    7400000,
    tasa_interes:      1.8,
    plazo_meses:       24,
    fecha_solicitud:   "2026-01-17",
    fecha_aprobacion:  "2026-01-24",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                28,
    usuario_id:        3,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  12500000,
    monto_aprobado:    12400000,
    tasa_interes:      1.3,
    plazo_meses:       18,
    fecha_solicitud:   "2025-04-07",
    fecha_aprobacion:  "2025-04-09",
    estado:            "aprobado",
    cuotas_pendientes: 8
  },
  {
    id:                29,
    usuario_id:        1,
    tipo_credito:      "Emergencia",
    monto_solicitado:  19500000,
    monto_aprobado:    19500000,
    tasa_interes:      1.0,
    plazo_meses:       24,
    fecha_solicitud:   "2025-08-25",
    fecha_aprobacion:  "2025-08-28",
    estado:            "aprobado",
    cuotas_pendientes: 3
  },
  {
    id:                30,
    usuario_id:        3,
    tipo_credito:      "Educativo",
    monto_solicitado:  8000000,
    monto_aprobado:    null,
    tasa_interes:      0.9,
    plazo_meses:       3,
    fecha_solicitud:   "2024-12-04",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                31,
    usuario_id:        1,
    tipo_credito:      "Convenio",
    monto_solicitado:  9500000,
    monto_aprobado:    9400000,
    tasa_interes:      1.2,
    plazo_meses:       36,
    fecha_solicitud:   "2024-08-07",
    fecha_aprobacion:  "2024-08-13",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                32,
    usuario_id:        3,
    tipo_credito:      "Emergencia",
    monto_solicitado:  19000000,
    monto_aprobado:    null,
    tasa_interes:      1.2,
    plazo_meses:       24,
    fecha_solicitud:   "2024-09-05",
    fecha_aprobacion:  null,
    estado:            "rechazado",
    cuotas_pendientes: 0
  },
  {
    id:                33,
    usuario_id:        2,
    tipo_credito:      "Vivienda",
    monto_solicitado:  8500000,
    monto_aprobado:    8200000,
    tasa_interes:      1.3,
    plazo_meses:       12,
    fecha_solicitud:   "2025-11-10",
    fecha_aprobacion:  "2025-11-14",
    estado:            "aprobado",
    cuotas_pendientes: 9
  },
  {
    id:                34,
    usuario_id:        2,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  5500000,
    monto_aprobado:    null,
    tasa_interes:      1.0,
    plazo_meses:       12,
    fecha_solicitud:   "2025-04-18",
    fecha_aprobacion:  null,
    estado:            "rechazado",
    cuotas_pendientes: 0
  },
  {
    id:                35,
    usuario_id:        1,
    tipo_credito:      "Libranza",
    monto_solicitado:  7000000,
    monto_aprobado:    6800000,
    tasa_interes:      1.2,
    plazo_meses:       18,
    fecha_solicitud:   "2026-01-05",
    fecha_aprobacion:  "2026-01-09",
    estado:            "aprobado",
    cuotas_pendientes: 16
  },
  {
    id:                36,
    usuario_id:        2,
    tipo_credito:      "Vacacional",
    monto_solicitado:  4000000,
    monto_aprobado:    null,
    tasa_interes:      1.5,
    plazo_meses:       6,
    fecha_solicitud:   "2026-02-01",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                37,
    usuario_id:        3,
    tipo_credito:      "Convenio",
    monto_solicitado:  11000000,
    monto_aprobado:    10500000,
    tasa_interes:      1.1,
    plazo_meses:       12,
    fecha_solicitud:   "2025-05-14",
    fecha_aprobacion:  "2025-05-17",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                38,
    usuario_id:        1,
    tipo_credito:      "Educativo",
    monto_solicitado:  16000000,
    monto_aprobado:    15500000,
    tasa_interes:      1.3,
    plazo_meses:       24,
    fecha_solicitud:   "2024-11-20",
    fecha_aprobacion:  "2024-11-24",
    estado:            "aprobado",
    cuotas_pendientes: 7
  },
  {
    id:                39,
    usuario_id:        2,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  9000000,
    monto_aprobado:    null,
    tasa_interes:      1.2,
    plazo_meses:       18,
    fecha_solicitud:   "2025-03-30",
    fecha_aprobacion:  null,
    estado:            "pendiente",
    cuotas_pendientes: 0
  },
  {
    id:                40,
    usuario_id:        3,
    tipo_credito:      "Vivienda",
    monto_solicitado:  13500000,
    monto_aprobado:    13000000,
    tasa_interes:      1.0,
    plazo_meses:       36,
    fecha_solicitud:   "2024-07-15",
    fecha_aprobacion:  "2024-07-19",
    estado:            "aprobado",
    cuotas_pendientes: 17
  },
  {
    id:                41,
    usuario_id:        1,
    tipo_credito:      "Libre Inversión",
    monto_solicitado:  2500000,
    monto_aprobado:    2500000,
    tasa_interes:      0.9,
    plazo_meses:       6,
    fecha_solicitud:   "2025-10-03",
    fecha_aprobacion:  "2025-10-06",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                42,
    usuario_id:        2,
    tipo_credito:      "Libranza",
    monto_solicitado:  17000000,
    monto_aprobado:    16500000,
    tasa_interes:      1.5,
    plazo_meses:       36,
    fecha_solicitud:   "2024-03-12",
    fecha_aprobacion:  "2024-03-16",
    estado:            "aprobado",
    cuotas_pendientes: 25
  },
  {
    id:                43,
    usuario_id:        3,
    tipo_credito:      "Convenio",
    monto_solicitado:  5000000,
    monto_aprobado:    null,
    tasa_interes:      1.8,
    plazo_meses:       12,
    fecha_solicitud:   "2025-08-08",
    fecha_aprobacion:  null,
    estado:            "rechazado",
    cuotas_pendientes: 0
  },
  {
    id:                44,
    usuario_id:        1,
    tipo_credito:      "Libranza",
    monto_solicitado:  20000000,
    monto_aprobado:    19500000,
    tasa_interes:      1.3,
    plazo_meses:       36,
    fecha_solicitud:   "2025-02-28",
    fecha_aprobacion:  "2025-03-04",
    estado:            "aprobado",
    cuotas_pendientes: 13
  },
  {
    id:                45,
    usuario_id:        2,
    tipo_credito:      "Educativo",
    monto_solicitado:  3500000,
    monto_aprobado:    3200000,
    tasa_interes:      1.0,
    plazo_meses:       6,
    fecha_solicitud:   "2024-06-01",
    fecha_aprobacion:  "2024-06-04",
    estado:            "pagado",
    cuotas_pendientes: 0
  },
  {
    id:                46,
    usuario_id:        3,
    tipo_credito:      "Vivienda",
    monto_solicitado:  10000000,
    monto_aprobado:    null,
    tasa_interes:      1.1,
    plazo_meses:       24,
    fecha_solicitud:   "2026-02-10",
    fecha_aprobacion:  null,
    estado:            "en_estudio",
    cuotas_pendientes: 0
  },
  {
    id:                47,
    usuario_id:        1,
    tipo_credito:      "Emergencia",
    monto_solicitado:  4500000,
    monto_aprobado:    4200000,
    tasa_interes:      1.2,
    plazo_meses:       12,
    fecha_solicitud:   "2024-10-17",
    fecha_aprobacion:  "2024-10-21",
    estado:            "aprobado",
    cuotas_pendientes: 1
  },
  {
    id:                48,
    usuario_id:        2,
    tipo_credito:      "Convenio",
    monto_solicitado:  6500000,
    monto_aprobado:    null,
    tasa_interes:      1.3,
    plazo_meses:       18,
    fecha_solicitud:   "2025-12-05",
    fecha_aprobacion:  null,
    estado:            "pendiente",
    cuotas_pendientes: 0
  },
  {
    id:                49,
    usuario_id:        3,
    tipo_credito:      "Vacacional",
    monto_solicitado:  14000000,
    monto_aprobado:    13500000,
    tasa_interes:      1.5,
    plazo_meses:       24,
    fecha_solicitud:   "2025-09-22",
    fecha_aprobacion:  "2025-09-26",
    estado:            "aprobado",
    cuotas_pendientes: 19
  },
  {
    id:                50,
    usuario_id:        2,
    tipo_credito:      "Libranza",
    monto_solicitado:  8000000,
    monto_aprobado:    7800000,
    tasa_interes:      1.0,
    plazo_meses:       18,
    fecha_solicitud:   "2024-05-30",
    fecha_aprobacion:  "2024-06-03",
    estado:            "pagado",
    cuotas_pendientes: 0
  }, 
];
